### PR TITLE
Issue #158: Use section title (with sectnums)

### PR DESCRIPTION
**Pull request by eiswind**
I found that in helpers.rb the section_title was already defined with sectnum support.
I'm not sure if it is as simple as that, but I changed the section template to use this helper.

### CODE REVIEW

**Comment by Mogztter** [comment]
Seems to be working as expected but you will need to update the tests:

- `test/doctest/outline.html`
- `test/doctest/section.html`

See: https://travis-ci.org/asciidoctor/asciidoctor-reveal.js/jobs/640352964

**Comment by eiswind** [comment]
Thanks for the hint :) There are tests...

**Comment by obilodeau** [comment]
Looking good! Awesome that `helpers.rb` already provided that.

Can you create a simple AsciiDoc file in `examples/` that demonstrates the feature in a minimal way and with accompanying doctest.

I don't think README documentation is necessary since this is an upstream documented feature of the language that we will now support.

**Comment by eiswind** [comment]
just added a simple example ..

**Pull request merged**
