### PR TITLE
Compile to JavaScript

### PR DESCRIPTION
**Pull request by ggrossetie**
- Compile the Reveal.js backend library (written in Ruby) to JavaScript using Opal
- Upgrade Asciidoctor.js to 1.5.5-3 and use the new wrapper API
- Use npm >= 3.x (with this version the transitive dependency `asciidoctor-template.js` is automatically fetched and therefore we can remove this step from the install procedure)
- Version `1.0.2.dev` is invalid in npm (replaced by `1.0.2-dev`)

### CODE REVIEW

**Comment by obilodeau** [comment]
Nice work! I'll adjust the `-dev` instead of `.dev` to the ruby version as well so that they are in sync.

**Comment by obilodeau** [comment]
I still haven't tested it (including build instructions) on my machine yet. Will do tomorrow.

Also, @mojavelinux what do you think?

**Comment by obilodeau** [comment]
Added two minimal changes. Tested both node and ruby packages: works as expected.

Keeping this open a few days to give @mojavelinux the chance to comment but otherwise, it's a :+1: from me.

**Comment by Mogztter** [comment]
Thanks @obilodeau :wink:

**Comment by Mogztter** [comment]
Thanks :tada:

**Pull request merged**
