### PR TITLE
Use H1 render title

### PR DESCRIPTION
**Pull request by lifei**
Title might be rendered into H1

### CODE REVIEW

**Comment by mojavelinux** [comment]
I totally agree, though this is already covered by #34 (still pending merge).

**Comment by lifei** [comment]
close due to duplicate

**Comment by mojavelinux** [comment]
Let's follow up on #34.

**Comment by obilodeau** [comment]
Re-opening since #34 isn't merged yet and I'm ready to push a fix just for this quick.

**Comment by obilodeau** [comment]
There are unrelated changes in that PR: whitespace and nested section changes. I'm going to close this and commit the h1 fix directly. Thanks for raising the issue!

**Pull request closed without merging**
