### PR TITLE
Update README.adoc

### PR DESCRIPTION
**Pull request by GrmpCerber**
Fixing asciidoctor/asciidoctor-reveal.js#68

### CODE REVIEW

**Comment by obilodeau** [comment]
I tried to reproduce your documentation with the adoc file you provided in #68 and I don't arrive at your results.

The `ifdef::backend-revealjs[=== !]` is visually rendered inline both in with the reveal.js back-end and the html back-end.

```
$ asciidoctor -V
Asciidoctor 1.5.4 [http://asciidoctor.org]
Runtime Environment (ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
```

I merged your PR in this branch and added my test case: https://github.com/asciidoctor/asciidoctor-reveal.js/compare/content-for-multiple-backends#diff-eb6036f05534957c98e164f1a6f20250R1

Can you tell me what I'm missing? Thanks!

**Comment by GrmpCerber** [comment]
I'm not 100% sure I understood your question correctly but I think I spotted an error in your test case (see my PR #80 )
PR #69 content was meant to be displayed by github.com as an hint on how to redact the adoc source, but you merged the raw content with my test file to create  your test case and ... BAM ! :)
In `ifndef::escapingSillyPreprocessor[ifdef::backend-revealjs[=== !]]` "escapingSillyPreprocessor" was meaning : github.com please stop trying to parse this because I want "ifdef::backend-revealjs[=== !]" to be displayed as is to the visitor

**Comment by obilodeau** [comment]
Got it! It works. Thanks!

Although your solution is very clever, you can escape a directive with a backslash:

```
\ifdef::backend-revealjs[=== !]
```

See http://asciidoctor.org/docs/user-manual/#preventing-substitutions

**Comment by GrmpCerber** [comment]
@obilodeau Sorry to have missed that :) `\` indeed seems easier to understand

**Pull request merged**
