### PR TITLE
resolves #7 support background options on title slide

### LINKED ISSUE #7: Background image doesn't work on the title slide
The background image, controlled by the `data-background` block attribute and related attributes, doesn't work on the title slide.

In general, the `<section>` element generated from the document title of the AsciiDoc document should have all the same capabilities as the `<section>` element generated from a section title.

### PR DESCRIPTION
**Pull request by mojavelinux**
* support background options on title slide
* use h1 for slide title instead of h2

### CODE REVIEW

**Comment by obilodeau** [comment]
Looks fair. Missing the documentation maybe?

**Comment by mojavelinux** [comment]
Yep, good point. I'll update the PR.

**Comment by obilodeau** [comment]
I'm glad you didn't merge this yet. I feel like we should do short aliases in addition to support upstream's naming. In exemple I really dislike the redundant `data-` prefix and I feel that data-background-size=cover or data-background-size=contain should be easier to type.

Asciidoc based on upstream's:

```asciidoc
[data-background-image=images/famous-joan.jpg, data-background-size=contain]
== !

a place to meet celebrities
```

Proposed fancier syntax:

```asciidoc
[background-image=famous-joan.jpg, background-size=contain]
== !

a place to meet celebrities
```

This removes redundant `data-` and adds `:imagesdir:` support.

But the ideal syntax would be:

```asciidoc
image:famous-joan.jpg[contain]
== !

a place to meet celebrities
```

Would it be possible? Detect the fact that the image inline macro is right above a section header? If so, patch in the data-background-stuff. Have most CSS3 background-size property values possible as macro parameters and honor width and height.

I'm interested in working on either "fancier" or "ideal" based on your input and I would add the documentation. Let me know.

**Comment by obilodeau** [comment]
Or maybe this one would be easier to implement?

```asciidoc
== !

image:famous-joan.jpg[background, contain]

a place to meet celebrities
```

**Comment by obilodeau** [comment]
I would throw this into the mix as well: https://github.com/obilodeau/asciidoctor-reveal.js/commit/ddfb13fc17e65b1d2eb535818b13166f5b67f933

**Comment by kubamarchwicki** [comment]
@obilodeau besides individual slides background - what about Dan's approach to the title's slide background. It's not as semantically lovely as `image::img.jpg[background, size=cover]` but still usefull. 
I haven't seen it in the #52 PR

--Kuba

**Comment by obilodeau** [comment]
Merged with some additional commits. The curious can view them here: https://github.com/asciidoctor/asciidoctor-reveal.js/commits/mojavelinux-issue-7

**Pull request merged**
