### PR TITLE
First release

### PR DESCRIPTION
**Pull request by obilodeau**
Are the changelog and instructions ok?

I have a rubygems.org account now so if you ACK this, I'll tag this commit and push.

### CODE REVIEW

**Comment by mojavelinux** [comment]
Looks good to me. In the future, we probably want to look into using rake to manage the release and also to run the tests. It's really not much harder to use than make and will be more approachable (and cross platform) for contributors.

**Comment by mojavelinux** [comment]
As for the commit messages, these are the templates I prefer to use:

1. Prepare %version% release
1. Release %version%
1. Begin development on next release

You can choose to skip 1 and just jump straight to 2. Feedback welcome.

**Comment by obilodeau** [comment]
* updated release instructions
* added release meta and credits

**Comment by mojavelinux** [comment]
Once you make the tag, you may also want to consider making a formal release on GitHub. Here's the template I've been using:

```
<Brief summary / overview>

## Distribution

* [RubyGem (asciidoctor-reveal.js)](https://rubygems.org/gems/asciidoctor-reveal.js)

## Changelog

<Paste changelog here, adjusting as necessary for it to be parsed as Markdown>

## Release meta

Released on: <date>
Released by: <@author>

Logs: [resolved issues](https://github.com/asciidoctor/asciidoctor-reveal.js/issues?q=milestone%3Av1.0.0)

## Credits

<Some thanks>
```

Feel free to revise. That's just a starting point. Obviously, automating this would be ideal. I just haven't gotten around to it yet. If there's a tool out there that can do it, don't hesitate to use it.

**Comment by mojavelinux** [comment]
Great job! :trophy:

**Pull request merged**
