### PR TITLE
Add favicon to HTML if its attribute is present in AsciiDoc

### PR DESCRIPTION
**Pull request by bbenno**
Source of added code can be found in asciidoctor repository
https://github.com/asciidoctor/asciidoctor/blob/3c7d2e8255d2f75dede0aab42ca32948ca4360e4/lib/asciidoctor/converter/html5.rb#L113-L123

rel #419

### CODE REVIEW

**Comment by Mogztter** [comment]
It looks good!
Would you mind adding a test?
You can create a file named `favicon.adoc` in `examples` directory:

```
// .favicon
// :include: //head/link[@rel="icon"]
// :header_footer:
= Favicon
:favicon:

== First Step

Check my favicon!
```

And then add `favicon.html` in `test/doctest`:

```html
<!-- .favicon -->
<link rel="icon" type="image/x-icon" href="favicon.ico">
```

It should do the trick!
Basically, you can create as many examples as you want and then you need to assert the HTML produced in `test/doctest`.

Some details about the comments in `favicon.adoc`.
Here you define a unique id:

```
// .favicon
```

Please note that you will need to use the same id in the HTML (`<!-- .favicon -->`)

This is a xpath to check only matching nodes (and not the complete HTML):

```
// :include: //head/link[@rel="icon"]
```

And last, we want to generate a full document with header and footer (i.e, including `<head>`):

```
:header_footer:
```

**Comment by bbenno** [comment]
> Would you mind adding a test?

Would be a pleasure! Basically I did not figure out the process of testing yesterday. So, thank you very much for the great support!

**Comment by bbenno** [comment]
@Mogztter I would like to add another test for the usage of a favicon with custom file path.
```adoc
// .custom-favicon
// :include: //head/link[@rel="icon"]
// :header_footer:
= Custom Favicon
:favicon: img/favicon.png
```
This should result in:
```html
<!-- .custom-favicon -->
<link rel="icon" type="image/png" href="img/favicon.png">
```

Is there a way to do this within the same test file `examples/favicon.adoc`?
As far as I can see this is not possible, isn't it?
If so, I would like to add the above test in `examples/favicon-custom.adoc`...

**Comment by Mogztter** [comment]
> Would be a pleasure! Basically I did not figure out the process of testing yesterday. So, thank you very much for the great support!

You're welcome!
We should probably add these instructions in https://docs.asciidoctor.org/reveal.js-converter/latest/project/hacking/ (https://github.com/asciidoctor/asciidoctor-reveal.js/blob/master/docs/modules/project/pages/hacking.adoc)

> I would like to add another test for the usage of a favicon with custom file path.

I think it's possible, `asciidoctor-doctest` (the underlying library) is using this document: `https://github.com/asciidoctor/asciidoctor-doctest/blob/master/data/examples/asciidoc/document.adoc`

Did you try the following?


```
// .favicon
// :include: //head/link[@rel="icon"]
// :header_footer:
= Favicon
:favicon:

// .custom-favicon
// :include: //head/link[@rel="icon"]
// :header_footer:
= Custom Favicon
:favicon: img/favicon.png
```

> Is there a way to do this within the same test file examples/favicon.adoc?
As far as I can see this is not possible, isn't it?
If so, I would like to add the above test in examples/favicon-custom.adoc

Indeed, if it does not work you can create `favicon-custom.adoc` (I'm fine with that).

**Comment by Mogztter** [comment]
LGTM, thanks @bbenno 👍

**Pull request merged**
