### PR TITLE
Added is-vcentered to our columns options

### PR DESCRIPTION
**Pull request by obilodeau**
It's a lot prettier when columns are unbalanced.

[Directly inspired by Bulma](https://bulma.io/documentation/columns/options/), good thing you mentioned it in the README @Mogztter!

### CODE REVIEW

**Comment by Mogztter** [comment]
I had a pull request in the making with `is-vcentered` but using a different use case.
I was using the following document:

```adoc
= Alignments
:revealjs_center: false
:revealjs_display: flex

[.is-vcentered]
== Vertical alignment

Here's a list of writers:

* Edgar Allen Poe
* Sheri S. Tepper
* Bill Bryson

// not sure about the name "is-vcentered-slide"
[.is-vcentered-slide]
== Vertical alignment (slide)

Here's a list of writers:

* Edgar Allen Poe
* Sheri S. Tepper
* Bill Bryson
```

In fact, there are multiple ways to vertically align content.

In the first slide, the space above the content (and the bottom of the title) and the space below the content (and the bottom of the slide) are equals:

valign1

In the second slide, the space above the top of the content (and the top of the title) and the space below the bottom of the content (and the bottom of the slide) are equals (ignoring the title height):

valign-slide2

And we can also vertically align content depending on the tallest column (as you did):
valign-column


It's somehow related because I want to make sure that the naming will be consistent and that we can support different alignements.
I'm not a big fan of `.is-vcentered-slide` maybe we should add an extra role on the content itself?

```
[.is-vcentered]
== Vertical alignment (slide)

[.absolute]
--
Here's a list of writers:

* Edgar Allen Poe
* Sheri S. Tepper
* Bill Bryson
--
```

**Comment by obilodeau** [comment]
> I'm not a big fan of `.is-vcentered-slide` maybe we should add an extra role on the content itself?

Why not just `.vcentered`? The `.is-vcentered` is a modifier on something that exists (`.columns` as in "the columns are vertically centered") but here we don't modify anything. I'm not convinced by the way. It's just a thought.

**Comment by Mogztter** [comment]
> Why not just .vcentered? The .is-vcentered is a modifier on something that exists (.columns as in "the columns are vertically centered")

I think we should stick with Bulma naming. They (hopefully) did some researches 😄
I was talking about how to make a distinction between "vertically align the content (within the content space)" and "vertically align the content within the whole slide".
I think `is-absolute` can work because that's basically what we are doing (ie. applies `position: absolute`) and it's less frequent use case (and it has a few drawbacks, for instance the content can overlap with the title since the position is absolute).

> but here we don't modify anything. I'm not convinced by the way. It's just a thought.

We do modify the alignment, right?

I think we can merge this pull request, I can follow-up with another pull request to implement "vertically align the content (within the content space)".
Since `is-absolute` is an edge case we can leave it for now.

**Comment by obilodeau** [comment]
> I think we should stick with Bulma naming. They (hopefully) did some researches 😄

Yes, of course, that comment was not about replacing `is-vcentered` it was about finding an alternative to `is-vcentered-slide`.

> I think `is-absolute` can work because that's basically what we are doing (ie. applies `position: absolute`) and it's less frequent use case (and it has a few drawbacks, for instance the content can overlap with the title since the position is absolute).

To me, this is too close to implementation detail. `is-absolute` doesn't give me a clue that the content is going to be vertically centered. I think we should try other things.

>> but here we don't modify anything. I'm not convinced by the way. It's just a thought.
>
> We do modify the alignment, right?

Of course :slightly_smiling_face:. I meant `.is-vcentered-slide` is not modifying *anything else* so we don't need to add the *is* on top of something existing. I think bulma uses `.is-` when it's an option on top of some existing base component: `.columns.is-vcentered`, `.column.is-one-third`, having `.is-one-third` alone is incomplete. One-third of what? `one-third-width` would make more sense if it's not an option on top of something else.

Just replying here while we are discussing this but I agree that this should be done in a follow-up PR.

> I think we can merge this pull request, I can follow-up with another pull request to implement "vertically align the content (within the content space)".
> Since `is-absolute` is an edge case we can leave it for now.

:+1: I'll merge later tonight (EST) then release.

**Pull request merged**
