### PR TITLE
Implemented subtitle partitioning

### PR DESCRIPTION
**Pull request by obilodeau**
See #70. Removed unnecessary HTML tags if no authors are provided too.

### CODE REVIEW

**Comment by mojavelinux** [comment]
Looks good. I noticed that you brought in a couple of functions you aren't yet using. Future use?

**Comment by obilodeau** [comment]
Hahaha no, it's a mistake. I'll remove it.

**Comment by obilodeau** [comment]
Done and applied author and preamble CSS classes to the relevant sections as a bonus.

**Comment by mojavelinux** [comment]
:+1: 

I don't think you need to say where the constants and functions come from. That's useful for the PR but probably not long-term. However, you could say at the top that this is similar to the Bespoke converter so that developers get the cue to study that converter as a reference (and vice versa).

**Pull request merged**
