### PR TITLE
fix unnecessary nested section in vertical sections

### PR DESCRIPTION
**Pull request by lifei**
`====` is rendered to nested section which is not correct.

### CODE REVIEW

**Comment by mojavelinux** [comment]
Thanks for this fix.

I think we could use a dynamic tag element to make this more concise. Something like:

```
*{tag: %(h#{@level > 1 ? 2 : 1})=title
```

Could you see if you can get the title output down to one line in each case?

**Comment by lifei** [comment]
You are right. I'm new to Ruby and slim. I do some modifications following your advice.

**Comment by obilodeau** [comment]
@lifei will you update your branch based on @mojavelinux's recommendations?

If not, it's ok I'll do it. Just let me know.

**Comment by lifei** [comment]
yes, I'll update the branch soon. thanks for remind.

**Comment by lifei** [comment]
done. please review the branch.

**Comment by mojavelinux** [comment]
At first glance that looks very reasonable to me. Could you remove the blank lines added in document.html.slim as they are not part of this change? Thanks!

**Comment by lifei** [comment]
yeah, sure

**Comment by lifei** [comment]
donw

**Comment by mojavelinux** [comment]
Thanks!

**Pull request merged**
