### PR TITLE
resolves #29 add table styles

### LINKED ISSUE #29: Tables do not listen to "grid" and "frames" options
Try this with `asciidoctor` with and without this backend:

``` asciidoc
[grid="all",frame="all",options="header"]
|==========================
| Test | Test 2 | Test 3
| More | Again  | And again
|==========================
```

The grid and frame shows up for regular asciidoctor, but not with reveal.js. It seems that there are some classes missing: 

``` css
table.grid-all th.tableblock,table.grid-all td.tableblock{border-width:0 1px 1px 0}
table.grid-all tfoot>tr>th.tableblock,table.grid-all tfoot>tr>td.tableblock{border-width:1px 1px 0 0}
table.grid-cols th.tableblock,table.grid-cols td.tableblock{border-width:0 1px 0 0}
table.grid-all *>tr>.tableblock:last-child,table.grid-cols *>tr>.tableblock:last-child{border-right-width:0}
table.grid-rows th.tableblock,table.grid-rows td.tableblock{border-width:0 0 1px 0}
table.grid-all tbody>tr:last-child>th.tableblock,table.grid-all tbody>tr:last-child>td.tableblock,table.grid-all thead:last-child>tr>th.tableblock,table.grid-rows tbody>tr:last-child>th.tableblock,table.grid-rows tbody>tr:last-child>td.tableblock,table.grid-rows thead:last-child>tr>th.tableblock{border-bottom-width:0}
table.grid-rows tfoot>tr>th.tableblock,table.grid-rows tfoot>tr>td.tableblock{border-width:1px 0 0 0}
table.frame-all{border-width:1px}
table.frame-sides{border-width:0 1px}
table.frame-topbot{border-width:1px 0}
```

Those rules show up in the regular asciidoctor document, but not the asciidoctor-reveal.js one.

### PR DESCRIPTION
**Pull request by ggrossetie**
resolves #29 #42 #56

### CODE REVIEW

**Comment by Mogztter** [comment]
Default | Aligns | Grid none, frame none
------------ | ------------- | -------------
table-default | aligns | grid-none-frame-none 


Frame none | Frame sides | Frame topbot
------------ | ------------- | -------------
frame-none | frame-sides | frame-topbot

Grid none | Grid cols | Grid rows
------------ | ------------- | -------------
grid-none | grid-cols  | grid-rows

**Comment by obilodeau** [comment]
This is amazing! :+1: for the example and the screenshots!

I think that by merging #287 I caused conflicts. Since you worked on both these PR recently, can you update here to fix the conflicts please?

**Comment by Mogztter** [comment]
Conflicts resolved, should I add an entry to the changelog?

**Comment by obilodeau** [comment]
Don't do the changelog, I can take care of it.

**Pull request merged**
